[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}

[project]
name = "randimania"
version = "0.5.0"
dependencies = [
    "importlib-metadata; python_version<'3.8'",
]

[project.scripts]
randimania = "randimania:main"

